import java.util.Scanner;

public class ConvertToLowerCase {
	//Method to convert the text to Lower case
	public static String convertToLowerCase(String str) {
		//StringBuilder to store the result
		StringBuilder sb = new StringBuilder(str);
		
		//Convert using loop and charAt()
		for(int i=0; i<sb.length(); i++) {
			char cTemp = sb.charAt(i);      //Temp character to store string characters
			if(cTemp >= 65 && cTemp <= (65+25)){  //if current index is in upperCase
				sb.setCharAt(i,(char)(cTemp+32));
			}
		}
		return sb.toString();  //Return String in uppper case
	}
	
	public static boolean compare(String str1,String str2) {
		if(str1.length() != str2.length()) {
			return false;
		}
		
		//Check using the loop
		for(int i=0;i<str1.length(); i++) {
			if(str1.charAt(i) != str2.charAt(i)){
				return false;              //if at any point two character at same index in both strings are not equal
			}
		}
		return true;
	}
	//Method to split text
	public static String[][] splitText(String str) { 
		
		int countWords = str.split("\\s").length; //to get the number of words
		//Store the result
		String[][] result = new String[countWords][2]; 
		int indexRow = 0;
		
		for(int i=0; i<str.length(); i++) {
			int count = 0;
			StringBuilder sb = new StringBuilder();
			while(i<str.length() && str.charAt(i) != ' '){
				sb.append(str.charAt(i));
				i++;
				count++; 
			}
			if(count > 0){
				result[indexRow][0] = sb.toString();
				result[indexRow][1] = Integer.toString(count);
				indexRow++;
			}
		}
		return result;
	}
		
	
	public static void main(String args[]){
	
		Scanner input = new Scanner(System.in);
		//Prompt the user to enter a string
		System.out.print("Enter a String: ");
		String str = input.nextLine();
		
		//Call method to convert to lower case
		String lowerCase1 = convertToLowerCase(str);
		
		//call pre-defined method
		String lowerCase2 = str.toLowerCase();
		
		//Compare both the strings generated by diffrent methods
		boolean result = compare(lowerCase1, lowerCase2);
		
		//Result of comparision
		if(result){
			System.out.print("Both the Methods are generating same result:  "+lowerCase1+"\n");
		}
		else {
			System.out.print("Both the string are diffrentS");
		}
		
		//Geting the word corresponding to their length
		String[][] words = splitText(str);
		
		for(int i=0; i<words.length; i++){
			System.out.println(words[i][0]+"  "+words[i][1]);
		}
		input.close();
	}
}