import java.util.Scanner;

public class ConvertToUpperCase {
	//Method to convert the text to upper case
	public static String convertToUpperCase(String str) {
		//StringBuilder to store the result
		StringBuilder sb = new StringBuilder(str);
		//Convert using loop and charAt()
		for(int i=0; i<sb.length(); i++) {
			char cTemp = sb.charAt(i);      //Temp character to store string characters
			if(cTemp >= 97 && cTemp <= (97+25)){  //if current index in in lower case
				sb.setCharAt(i,(char)(cTemp-32));
			}
		}
		return sb.toString();  //Return String in uppper case
	}
	
	public static boolean compare(String str1,String str2) {
		if(str1.length() != str2.length()) {
			return false;
		}
		
		//Check using the loop
		for(int i=0;i<str1.length(); i++) {
			if(str1.charAt(i) != str2.charAt(i)){
				return false;              //if at any point two character at same index in both strings are not equal
			}
		}
		return true;
	}
	
	public static void main(String args[]){
	
		Scanner input = new Scanner(System.in);
		//Prompt the user to enter a string
		System.out.print("Enter a String: ");
		String str = input.nextLine();
		
		//Call method to convert to uppper case
		String upperCase1 = convertToUpperCase(str);
		
		//call pre-defined method
		String upperCase2 = str.toUpperCase();
		
		//Compare both the strings generated by diffrent methods
		boolean result = compare(upperCase1, upperCase2);
		
		//Result
		if(result){
			System.out.print("Both the Methods are generating same result:  "+upperCase1);
		}
		else {
			System.out.print("Both the string are diffrentS");
		}
	
		input.close();
	}
}